// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHGelXNvz-1zfNeMRQj_bsU_Lw0x2mKs',
    appId: '1:96263660495:web:1b6f432793faf7d7b168ba',
    messagingSenderId: '96263660495',
    projectId: 'time-tracker-dff0b',
    authDomain: 'time-tracker-dff0b.firebaseapp.com',
    storageBucket: 'time-tracker-dff0b.appspot.com',
    measurementId: 'G-B87B94PFCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaC0-RP_b8qEpryJnTPxMKjF1zBMbFOR8',
    appId: '1:96263660495:android:4435ba701828b51fb168ba',
    messagingSenderId: '96263660495',
    projectId: 'time-tracker-dff0b',
    storageBucket: 'time-tracker-dff0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfFRwWj9K75eQXLE92Ydxo7D1iMzx39k',
    appId: '1:96263660495:ios:5e3d8275dee6b088b168ba',
    messagingSenderId: '96263660495',
    projectId: 'time-tracker-dff0b',
    storageBucket: 'time-tracker-dff0b.appspot.com',
    iosClientId: '96263660495-l1dap0vtsuq18702ta1tmf59evn5ad71.apps.googleusercontent.com',
    iosBundleId: 'time.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfFRwWj9K75eQXLE92Ydxo7D1iMzx39k',
    appId: '1:96263660495:ios:5e3d8275dee6b088b168ba',
    messagingSenderId: '96263660495',
    projectId: 'time-tracker-dff0b',
    storageBucket: 'time-tracker-dff0b.appspot.com',
    iosClientId: '96263660495-l1dap0vtsuq18702ta1tmf59evn5ad71.apps.googleusercontent.com',
    iosBundleId: 'time.tracker',
  );
}
